let category = [
   "Makeup","Beauty","Hair","Hand & Feet","Spa"
];
let subCategory = {
    1:["Light MakeUp"],
    2:["Body Wax","Facials","Bleach","Threading"],
    3:["Cut & Style","Hair Straightening","Hair Color","Hair Spa","Color Touch Up"],
    4:["Mani/ Pedi"],
    5:["Massages","Scrubs & Wraps","Express Spa"]
}
[
    {category: 'Makeup', subCategory: "Light MakeUp",gender:"M"},
    {category: 'Beauty', subCategory: "Body Wax",gender:"M"},
    {category: 'Beauty', subCategory: "Facials",gender:"M"},
    {category: 'Beauty', subCategory: "Bleach",gender:"M"},
    {category: 'Beauty', subCategory: "Threading",gender:"M"},
    {category: 'Hair', subCategory: "Cut & Style",gender:"M"},
    {category: 'Hair', subCategory: "Hair Straightening",gender:"M"},
    {category: 'Hair', subCategory: "Hair Color",gender:"M"},
    {category: 'Hair', subCategory: "Hair Spa",gender:"M"},
    {category: 'Hair', subCategory: "Color Touch Up",gender:"M"},
    {category: 'Hand & Feet', subCategory: "Mani/ Pedi",gender:"M"},
    {category: 'Spa', subCategory: "Massages",gender:"M"},
    {category: 'Spa', subCategory: "Scrubs & Wraps",gender:"M"},
    {category: 'Spa', subCategory: "Express Spa",gender:"M"}
]
let miniCategory = {
    1:{
        1:["Male Makeup"]
    },
    2:{
        1:["-Hair Trimming Underarms","-Hair Trimming Full Body","-Hair Trimming Arms","-Hair Trimming Back","-Hair Trimming Chest","-Hair Trimming Legs","-Full Body","-Half Front/Back","-Full Front / Back","-Full Legs","-Full Arms+Legs+Underarms","-Full Arms","-Underarms"],
        2:["-Moor Mud Mask","-Face Massage","-Rubber Mask 2040 Collagen Mask","-Rubber Mask 2010 Green Tea Mask","-Rubber Mask 2030 Vitamin C Mask","-Rubber Mask 2020 Rose Mask","-Facial (Skin Co. New York / INARA)","-Men Facial","-Cheryl's Glovite","-Cheryl's Tanclear","-Cheryl's Oxyblast","-Cheryl's Clariglow","-Cheryl's HydraMoist Kit","-Cheryl's ClariNzyme","-Cheryl's SensiNzyme","-Cheryl's SensiAcne","Clean Up-Skin Co Clean Up","Luxury Facial-4 Layer Whitening","Luxury Facial-Luxury Skin Co Facial","Luxury Facial-Luxury O2C2 Radiance Treatment","Luxury Facial-Luxury Cheryl's Dermalite Fairness Treatment","Premium Facial-Premium Skin Co Facial","Premium Facial-Premium Facial - Trendsetter","Premium Facial-Premium Cheryl's Sensiglow Facial","Premium Facial-Premium Cheryl's Vitalift Facial"],
        3:["-Arms","-Face & Neck","-Legs-Anti Tan Pack","-Full Front/Back","-Full Body","-Tummy Front/Back","-Neck & Blouse Line","-Cheryl's Oxyderm","-Cheryl's Oxyderm Bleach"],
        4:["-Forehead/Chin","-Eyebrows+Upper Lips","-Eyebrows/Upper lips Katori Wax","-Sides & Jawline (Katori Wax)","-Eyebrows-Upper Lips","-Full Face","-Forehead/Chin (Katori Wax)","-Sides & Jawline","-Eyebrows (Katori Wax)","-Upper Lips (Katori Wax)","-Full Face (Katori Wax)"]
    },
    3:{
        1:["-Children Hair Cut (Under 10)","-Cut & Blow-dry","-Shampoo & Conditioner","-Jura/Updo","-Fringe/Flicks","-Blowdry Straight","-Steampod Ironing","-Blowdry","-Tongs/Ringlets/Irons","-Female Hair Cut - Trendsetter","-Blowdry - Trendsetter","-K Wash","-Female Free Hair Cut"],
        2:["-Rebonding","-Smart Bond","-Straightening","-Keratin","-Smoothening","-Smart Bond Standalone","-Keratin+Hair Cut"],
        3:["-Highlights Full Head","-Global Color","-Global Color","-Color Change","-Creative Color","-Per Streak Highlight Chunks","-Highlights - Half Head","-Pre Lightening"],
        4:["-Pro Fibre Serioxyl","-Cheryl's Face lifting Complex","-Cheryl's Skin Lightening Complex","-Cheryl's Hydrating complex",
        "Expert Treatments-Anit Dandruff Treatment","Expert Treatments-Loreal Expert Treatment","Expert Treatments-Loreal Expert Rituals","Instant Care - Expert Treatments-Power Mix Force","Instant Care - Expert Treatments-Lipidium Primer","Instant Care - Expert Treatments-Power Mix Reair","Instant Care - Expert Treatments-Power Mix Color","Instant Care - Expert Treatments-Pure Balance/Sensicalm/Anti Dundruff","Kerastase Experiencce-Express Intensive Nourishment 60 Min Experience","Kerastase Experiencce-Densifying Ritual 60 Min Experience","Kerastase Experiencce-Volumising Ritual 60 Min Experience","Kerastase Experiencce-Express Intensive Nourishment 60 Min Experience","Kerastase Experiencce-Smoothing Ritual 60 Minexperience","Kerastase Experiencce-Strengthening Ritual 60 Min Experience","Kerastase Experiencce-Intensive Nourishment Ritual 60 Min Experience","Kerastase Experiencce-Sensidote Soothing Ritual 60 Min Experience","Kerastase Experiencce-Curl Design Ritual 60 Min Experience","Kerastase Express-Discipline Ritual 30 Min Express","Kerastase Express-Densifying Ritual 30 Min Express","Kerastase Express-Eu Liquid Gold Scented Oil Ritual 45 Min Express","Kerastase Express-Chronologiste Fragrant Blow Dry 30 Min Express","Kerastase Express-Couture Styling 30 Min Express","Kerastase Express-Express Intensive Nourishment 30 Min Express","Kerastase Express-Elixir Ultime Sublime Precious Oil Ritual 30 Min Express","Kerastase Express-Anti Dandruff Ritual 30 Min Express","Kerastase VIP-Chronologiste Caviar Ritual Vip Rituals 90 Min Vip","Kerastase VIP-Elixir Ultime Silk Veil Oil Ritual 90 Min Vip","Kerastase VIP-Keratherapy Vip Ritual 75 Minvip","Kerastase VIP-Morpho Keratine Vip Ritual 90 Min Vip","Mythic Rituals-Mythic Repair","Spa-Hair Spa (Concentrate)","Spa-Loreal Hair Spa","Spa-Fusio Dose Ritual"],
        5:["-Root Touch Up","-Color Refresh"]
    },
    4:{
        1:["-Paraffin Wax Hand","-Paraffin Wax Feet","-Feet Cleaning","-Cheryl's Heel Peel Kit","Manicure-Classic Manicure","Manicure-Classic Skin Co Manicure","Manicure-Premium Skin Co Manicure","Manicure-Luxury Skin Co Manicure","Manicure & Pedicure-Luxury Inara Manicure & Pedicure","Manicure & Pedicure-Classic Skin Co Manicure & Pedicure","Manicure & Pedicure-Premium Skin Co Manicure & Pedicure","Manicure & Pedicure-Luxury Skin Co Manicure & Pedicure","Pedicure-Classic Skin Co Pedicure","Pedicure-Premium Skin Co Pedicure","Pedicure-Luxury Skin Co Pedicure"]
    },
    5:{
        1:["-Signature","-Aroma","-Deep Tissue"],
        2:["-Sea Salt Rose","-Kokum Butter & Honey"],
        3:["-Head,Neck & Shoulder","-Foot Reflexology"]
    }
}


export let maleData = [
{name:"-Signature",subCategory:"Massages", category:"Spa",gender:"M"},
{name:"-Aroma",subCategory:"Massages", category:"Spa",gender:"M"},
{name:"-Deep Tissue",subCategory:"Massages", category:"Spa",gender:"M"},
{name:"-Sea Salt Rose", subCategory:"Scrubs & Wraps",category:"Spa",gender:"M"},
{name:"-Kokum Butter & Honey", subCategory:"Scrubs & Wraps",category:"Spa",gender:"M"},
{name:"-Head,Neck & Shoulder", subCategory:"Express Spa",category:"Spa",gender:"M"},
{name:"-Foot Reflexology", subCategory:"Express Spa",category:"Spa",gender:"M"},
{name:"-Paraffin Wax Hand",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"-Paraffin Wax Feet",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"-Feet Cleaning",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"-Cheryl's Heel Peel Kit",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"Manicure-Classic Manicure",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"Manicure-Classic Skin Co Manicure",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"Manicure-Premium Skin Co Manicure",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"Manicure-Luxury Skin Co Manicure",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"Manicure & Pedicure-Luxury Inara Manicure & Pedicure",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"Manicure & Pedicure-Classic Skin Co Manicure & Pedicure",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"Manicure & Pedicure-Premium Skin Co Manicure & Pedicure",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"Manicure & Pedicure-Luxury Skin Co Manicure & Pedicure",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"Pedicure-Classic Skin Co Pedicure",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"Pedicure-Premium Skin Co Pedicure",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"Pedicure-Luxury Skin Co Pedicure",subCategory:"Mani/ Pedi",category:"Hand & Feet",gender:"M"},
{name:"-Root Touch Up",subCategory:"Color Touch Up",category:"Hair",gender:"M"},
{name:"-Color Refresh",subCategory:"Color Touch Up",category:"Hair",gender:"M"},
{name:"-Pro Fibre Serioxyl",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"-Cheryl's Face lifting Complex",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"-Cheryl's Skin Lightening Complex",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"-Cheryl's Hydrating complex",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Expert Treatments-Anit Dandruff Treatment",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Expert Treatments-Loreal Expert Treatment",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Expert Treatments-Loreal Expert Rituals",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Instant Care - Expert Treatments-Power Mix Force",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Instant Care - Expert Treatments-Lipidium Primer",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Instant Care - Expert Treatments-Power Mix Reair",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Instant Care - Expert Treatments-Power Mix Color",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Instant Care - Expert Treatments-Pure Balance/Sensicalm/Anti Dundruff",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Experiencce-Express Intensive Nourishment 60 Min Experience",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Experiencce-Densifying Ritual 60 Min Experience",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Experiencce-Volumising Ritual 60 Min Experience",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Experiencce-Express Intensive Nourishment 60 Min Experience",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Experiencce-Smoothing Ritual 60 Minexperience",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Experiencce-Strengthening Ritual 60 Min Experience",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Experiencce-Intensive Nourishment Ritual 60 Min Experience",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Experiencce-Sensidote Soothing Ritual 60 Min Experience",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Experiencce-Curl Design Ritual 60 Min Experience",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Express-Discipline Ritual 30 Min Express",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Express-Densifying Ritual 30 Min Express",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Express-Eu Liquid Gold Scented Oil Ritual 45 Min Express",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Express-Chronologiste Fragrant Blow Dry 30 Min Express",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Express-Couture Styling 30 Min Express",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Express-Express Intensive Nourishment 30 Min Express",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Express-Elixir Ultime Sublime Precious Oil Ritual 30 Min Express",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase Express-Anti Dandruff Ritual 30 Min Express",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase VIP-Chronologiste Caviar Ritual Vip Rituals 90 Min Vip",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase VIP-Elixir Ultime Silk Veil Oil Ritual 90 Min Vip",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase VIP-Keratherapy Vip Ritual 75 Minvip",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Kerastase VIP-Morpho Keratine Vip Ritual 90 Min Vip",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Mythic Rituals-Mythic Repair",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Spa-Hair Spa (Concentrate)",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Spa-Loreal Hair Spa",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"Spa-Fusio Dose Ritual",subCategory:"Hair Spa",category:"Hair",gender:"M"},
{name:"-Highlights Full Head",subCategory:"Hair Color",category:"Hair",gender:"M"},
{name:"-Global Color",subCategory:"Hair Color",category:"Hair",gender:"M"},
{name:"-Global Color",subCategory:"Hair Color",category:"Hair",gender:"M"},
{name:"-Color Change",subCategory:"Hair Color",category:"Hair",gender:"M"},
{name:"-Creative Color",subCategory:"Hair Color",category:"Hair",gender:"M"},
{name:"-Per Streak Highlight Chunks",subCategory:"Hair Color",category:"Hair",gender:"M"},
{name:"-Highlights - Half Head",subCategory:"Hair Color",category:"Hair",gender:"M"},
{name:"-Pre Lightening",subCategory:"Hair Color",category:"Hair",gender:"M"},
{name:"-Rebonding",subCategory:"Hair Straightening",category:"Hair",gender:"M"},
{name:"-Smart Bond",subCategory:"Hair Straightening",category:"Hair",gender:"M"},
{name:"-Straightening",subCategory:"Hair Straightening",category:"Hair",gender:"M"},
{name:"-Keratin",subCategory:"Hair Straightening",category:"Hair",gender:"M"},
{name:"-Smoothening",subCategory:"Hair Straightening",category:"Hair",gender:"M"},
{name:"-Smart Bond Standalone",subCategory:"Hair Straightening",category:"Hair",gender:"M"},
{name:"-Keratin+Hair Cut",subCategory:"Hair Straightening",category:"Hair",gender:"M"},
{name:"-Children Hair Cut (Under 10)",subCategory:"Cut & Style",category:"Hair",gender:"M"},
{name:"-Cut & Blow-dry",subCategory:"Cut & Style",category:"Hair",gender:"M"},
{name:"-Shampoo & Conditioner",subCategory:"Cut & Style",category:"Hair",gender:"M"},
{name:"-Jura/Updo",subCategory:"Cut & Style",category:"Hair",gender:"M"},
{name:"-Fringe/Flicks",subCategory:"Cut & Style",category:"Hair",gender:"M"},
{name:"-Blowdry Straight",subCategory:"Cut & Style",category:"Hair",gender:"M"},
{name:"-Steampod Ironing",subCategory:"Cut & Style",category:"Hair",gender:"M"},
{name:"-Blowdry",subCategory:"Cut & Style",category:"Hair",gender:"M"},
{name:"-Tongs/Ringlets/Irons",subCategory:"Cut & Style",category:"Hair",gender:"M"},
{name:"-Female Hair Cut - Trendsetter",subCategory:"Cut & Style",category:"Hair",gender:"M"},
{name:"-Blowdry - Trendsetter",subCategory:"Cut & Style",category:"Hair",gender:"M"},
{name:"-K Wash",subCategory:"Cut & Style",category:"Hair",gender:"M"},
{name:"-Female Free Hair Cut",subCategory:"Cut & Style",category:"Hair",gender:"M"},
{name:"-Forehead/Chin",subCategory:"Threading",category:"Beauty",gender:"M"},
{name:"-Eyebrows+Upper Lips",subCategory:"Threading",category:"Beauty",gender:"M"},
{name:"-Eyebrows/Upper lips Katori Wax",subCategory:"Threading",category:"Beauty",gender:"M"},
{name:"-Sides & Jawline (Katori Wax)",subCategory:"Threading",category:"Beauty",gender:"M"},
{name:"-Eyebrows-Upper Lips",subCategory:"Threading",category:"Beauty",gender:"M"},
{name:"-Full Face",subCategory:"Threading",category:"Beauty",gender:"M"},
{name:"-Forehead/Chin (Katori Wax)",subCategory:"Threading",category:"Beauty",gender:"M"},
{name:"-Sides & Jawline",subCategory:"Threading",category:"Beauty",gender:"M"},
{name:"-Eyebrows (Katori Wax)",subCategory:"Threading",category:"Beauty",gender:"M"},
{name:"-Upper Lips (Katori Wax)",subCategory:"Threading",category:"Beauty",gender:"M"},
{name:"-Full Face (Katori Wax)",subCategory:"Threading",category:"Beauty",gender:"M"},
{name:"-Arms",subCategory:"Bleach",category:"Beauty",gender:"M"},
{name:"-Face & Neck",subCategory:"Bleach",category:"Beauty",gender:"M"},
{name:"-Legs-Anti Tan Pack",subCategory:"Bleach",category:"Beauty",gender:"M"},
{name:"-Full Front/Back",subCategory:"Bleach",category:"Beauty",gender:"M"},
{name:"-Full Body",subCategory:"Bleach",category:"Beauty",gender:"M"},
{name:"-Tummy Front/Back",subCategory:"Bleach",category:"Beauty",gender:"M"},
{name:"-Neck & Blouse Line",subCategory:"Bleach",category:"Beauty",gender:"M"},
{name:"-Cheryl's Oxyderm",subCategory:"Bleach",category:"Beauty",gender:"M"},
{name:"-Cheryl's Oxyderm Bleach",subCategory:"Bleach",category:"Beauty",gender:"M"},
{name:"-Moor Mud Mask",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Face Massage",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Rubber Mask 2040 Collagen Mask",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Rubber Mask 2010 Green Tea Mask",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Rubber Mask 2030 Vitamin C Mask",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Rubber Mask 2020 Rose Mask",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Facial (Skin Co. New York / INARA)",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Men Facial",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Cheryl's Glovite",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Cheryl's Tanclear",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Cheryl's Oxyblast",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Cheryl's Clariglow",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Cheryl's HydraMoist Kit",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Cheryl's ClariNzyme",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Cheryl's SensiNzyme",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Cheryl's SensiAcne",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"Clean Up-Skin Co Clean Up",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"Luxury Facial-4 Layer Whitening",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"Luxury Facial-Luxury Skin Co Facial",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"Luxury Facial-Luxury O2C2 Radiance Treatment",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"Luxury Facial-Luxury Cheryl's Dermalite Fairness Treatment",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"Premium Facial-Premium Skin Co Facial",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"Premium Facial-Premium Facial - Trendsetter",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"Premium Facial-Premium Cheryl's Sensiglow Facial",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"Premium Facial-Premium Cheryl's Vitalift Facial",subCategory:"Facials",category:"Beauty",gender:"M"},
{name:"-Hair Trimming Underarms",subCategory:"Body Wax",category:"Beauty",gender:"M"},
{name:"-Hair Trimming Full Body",subCategory:"Body Wax",category:"Beauty",gender:"M"},
{name:"-Hair Trimming Arms",subCategory:"Body Wax",category:"Beauty",gender:"M"},
{name:"-Hair Trimming Back",subCategory:"Body Wax",category:"Beauty",gender:"M"},
{name:"-Hair Trimming Chest",subCategory:"Body Wax",category:"Beauty",gender:"M"},
{name:"-Hair Trimming Legs",subCategory:"Body Wax",category:"Beauty",gender:"M"},
{name:"-Full Body",subCategory:"Body Wax",category:"Beauty",gender:"M"},
{name:"-Half Front/Back",subCategory:"Body Wax",category:"Beauty",gender:"M"},
{name:"-Full Front / Back",subCategory:"Body Wax",category:"Beauty",gender:"M"},
{name:"-Full Legs",subCategory:"Body Wax",category:"Beauty",gender:"M"},
{name:"-Full Arms+Legs+Underarms",subCategory:"Body Wax",category:"Beauty",gender:"M"},
{name:"-Full Arms",subCategory:"Body Wax",category:"Beauty",gender:"M"},
{name:"-Underarms",subCategory:"Body Wax",category:"Beauty",gender:"M"},
{name:"Male Makeup",subCategory:"Light MakeUp",category:"Makeup",gender:"M"}
]

